### ISSUE TITLE
chord transposer

### ISSUE THREAD

**Issue by johnnis33** [jpotterm/google-apps-chord-transposer#1] opened 2015-12-21 21:25 UTC
Now no work good this app move the chords!

**Comment by jpotterm** [comment] 2015-12-24 04:22
Can you give me an example document?

**Comment by jpotterm** [comment] 2015-12-24 04:31
Also just a note: if you're using tabs they aren't supported, so you should switch to spaces.

**Comment by jpotterm** [comment] 2016-01-20 15:34
I'm closing this as could not reproduce. If you provide more information I may re-open it.

**Closed as completed by jpotterm** 2016-01-20 15:34 UTC
